### ISSUE TITLE
Pasting images directly into the editor

### ISSUE THREAD

**Issue by Cerzi** [springload/draftail#142] opened 2018-03-14 13:00 UTC
I'm looking to paste mixed media articles from a local doc file into draftail, and have them handled in some custom way (ideally auto-uploaded to the server at the same time as being set inline).

Are there any features in place that might enable this, or would this be a case of looking into creating a custom entity?

Alternatively, are there any features in place to be able to paste images in from other websites and automatically set their src attributes?  I believe this was possible in the draft.js used by the previous versions of Wagtail.

**Comment by Cerzi** [comment] 2018-03-19 12:08
This is incredibly useful information, thank you!

**Comment by Cerzi** [comment] 2018-03-19 15:44
I have the pasting functionality back in the draftail editor now, however there seems to be some issues with this approach coming from the rest of the wagtail pipeline.  That is, images without an id attr cause problems due to these lines:

https://github.com/wagtail/wagtail/blob/07bcf4502761d946e7d932b3ab943c252fa76da9/wagtail/images/rich_text.py#L13-L25

Are there any clean ways to work around this?

**Comment by thibaudcolas** [comment] 2018-03-19 21:25
👏 yep, you probably need to override https://github.com/wagtail/wagtail/blob/master/wagtail/images/wagtail_hooks.py#L86-L100 and the likes to support hotlinked images.

For the auto-upload image block with React and Draft.js, I can provide you with some examples to help. Here is what a very basic image block would look like:

```js
// Assuming you're using Wagtail’s built-in React.
const React = window.React;

class ImageBlock extends React.Component {
  render() {
    const { blockProps } = this.props;
    const { entity } = blockProps;
    const { src, alt } = entity.getData();

    return React.createElement('img', {
        className: 'ImageBlock',
        src: src,
        alt: alt,
        width: '256',
    });
  }
}
```

Once defined, you'd need to register this like described in [the docs](http://docs.wagtail.io/en/v2.0/advanced_topics/customisation/extending_draftail.html).

Building upon this with an upload feature:

```js
// Assuming you're using Wagtail’s built-in React.
const React = window.React;
const DraftUtils = window.DraftUtils;

const imageUpload = (data, successCallback) => {
    // Do the upload first, then call the callback with the final image data.
    const uploadedImageData = {};
    successCallback(uploadedImageData);
};

class ImageBlock extends React.Component {
    constructor(props) {
        this.state = {
            isUploading: false,
        };

        this.onImageUploaded = this.onImageUploaded.bind(this);
    }

    componentDidMount() {
        const { blockProps } = this.props;
        const { entity } = blockProps;
        const data = entity.getData();

        // The image is hotlinked from its source.
        if (!data.id) {
            // Here: upload the image to the server.
            imageUpload(data, this.onImageUploaded);

            this.setState({
                isUploading: true,
            });
        }
    }

    onImageUploaded(uploadedImageData) {
        const { block, blockProps } = this.props;
        const { editorState, onChange } = blockProps;

        onChange(DraftUtils.updateBlockEntity(editorState, block, uploadedImageData));

        this.setState({
            isUploading: false,
        });
    }

    render() {
        const { blockProps } = this.props;
        const { entity } = blockProps;
        const { src, alt } = entity.getData();
        const { isUploading } = this.state;

        return React.createElement('img', {
            className: `ImageBlock${isUploading ? ' ImageBlock--uploading' : ''}`,
            src: src,
            alt: alt,
            width: '256',
        });
    }
}
```

That's probably as much as I can help with this for now, but let me know how it goes. If your code is open-source I could also directly have a look.

**Comment by Cerzi** [comment] 2018-03-19 21:44
So far I've been mostly trial and erroring it off the back of the [example](http://docs.wagtail.io/en/v2.0/advanced_topics/customisation/extending_draftail.html#creating-new-entities) posted in the docs.  Here's the pretty rough react code I have so far:


```
const React = window.React;
const Modifier = window.DraftJS.Modifier;
const EditorState = window.DraftJS.EditorState;

class ImageSource extends React.Component {
    componentDidMount() {
        const { editorState, entityType, onComplete } = this.props;

        const content = editorState.getCurrentContent();
        const selection = editorState.getSelection();
        const src = window.prompt('Image URL');
        // Uses the Draft.js API to create a new entity with the right data.
        const contentWithEntity = content.createEntity(entityType.type, 'IMMUTABLE', {
            src: src,
        });
        const entityKey = contentWithEntity.getLastCreatedEntityKey();

        const newContent = Modifier.replaceText(content, selection, text, null, entityKey);
        const nextState = EditorState.push(editorState, newContent, 'insert-characters');
        onComplete(nextState);
    }

    render() {
        return null;
    }
}

const Image = (props) => {
    const { entityKey, contentState } = props;
    const data = contentState.getEntity(entityKey).getData();
    return React.createElement('img', {
        src: data.src,
        alt: data.alt
    });
};

window.draftail.registerPlugin({
    type: 'AUTOIMAGE',
    source: ImageSource,
    decorator: Image,
});`
```

The main concept I'm wrestling with right now is:

- How can I get ImageSource called on-the-fly (as images are pasted into the editor)? So far with my limited understanding I can only get this code to execute off the back of a toolbar click (created a new icon for "upload image from URL". 

While I get my head around that though, the "manual" approach to adding hotlinked images will still allow me to test and implement the upload functionality, so will focus on that for now.  Thanks again for your help & input here - once I've got my head around this I'll be happy to post up the full source if it'd be any use to the project.

**Comment by thibaudcolas** [comment] 2018-03-21 22:07
I haven't really had the time to go through your code but I think the problem is just the snippet you posted, which needs to be:

```js
window.draftail.registerPlugin({
    type: 'IMAGE',
    block: ImageBlock,
});
```

`source` is what is rendered when you click the "Image" button in the toolbar. `block` is what's displayed on the page. You probably need a `source` as well (maybe Wagtail’s), but if you were to only ever paste images and never use the toolbar the `source` implementation technically wouldn't be used.

**Comment by Cerzi** [comment] 2018-03-21 22:40
Aha!  Am backlogged with other projects for the next few days but I think that might be all I needed to get things working.  Must say though, the "source" term was confusing the hell outta me - didn't seem to be any clear definition in any related docs.  Although now you've described it, the word makes perfect sense.  Probably just my lack of experience dealing with draftjs/react.

Will let ya know how I get on next week.  Thanks again!

**Comment by Cerzi** [comment] 2018-03-23 13:37
Quick question (yeah I'm making this into a real slog!):  is DraftUtils supposed to be included or is it an external package?  If the latter, I'm struggling to find it (nearest thing is Draftjs-Utils which doesn't contain the UpdateBlockEntity function).

I can probably just write the same logic manually but chances are I'm missing something obvious here.

Problematic line:

```const DraftUtils = window.DraftUtils;``` is null

(this is all using Wagtail 2.0)

**Comment by thibaudcolas** [comment] 2018-03-23 14:24
My bad, `window.DraftUtils` is not a thing (but it probably should be) – your best bet for now is to copy-paste that function in your own code. Source: https://github.com/springload/draftail/blob/8284dae4d9ff4de89bf1fe913d7d4f2cb06e08c5/lib/api/DraftUtils.js#L86-L107

```js
    /**
     * Updates a given atomic block's entity, merging new data with the old one.
     */
    updateBlockEntity(editorState, block, data) {
        const content = editorState.getCurrentContent();
        let nextContent = content.mergeEntityData(block.getEntityAt(0), data);


        // To remove in Draft.js 0.11.
        // This is necessary because entity data is still using a mutable, global store.
        nextContent = Modifier.mergeBlockData(
            nextContent,
            new SelectionState({
                anchorKey: block.getKey(),
                anchorOffset: 0,
                focusKey: block.getKey(),
                focusOffset: block.getLength(),
            }),
            {},
        );


        return EditorState.push(editorState, nextContent, 'apply-entity');
    },
```

**Comment by Cerzi** [comment] 2018-03-26 17:22
Thanks to your assistance, I've got the basic functionality up and running now.  Here's the bulk of the code, in case it's of use to anyone else looking to do something similar.
[React](https://gist.github.com/Cerzi/01ede72db7d58a23c7482af01d22ef47)
[Views - ajax handler](https://gist.github.com/Cerzi/c89536ed91cab2a611f798e688897469)
[Models - extended wagtail Image model for tracking urls and keeping url logic in one place](https://gist.github.com/Cerzi/4fd32806db1f2f0daa01652ce8cac61e)

Next thing I'll be wrestling with is how to formally reference the page that the image has been pasted into.  The issue is that when the image is actually uploaded, and the image obj created in the db, there isn't necessarily the corresponding page in the db (if the editor has not saved first draft or published).  So I'll need to do a check when the page itself is saved, and similarly will potentially need to set up a cron job or something to clean up uploaded images that for drafts that were never actually saved.

**Comment by thibaudcolas** [comment] 2018-03-30 21:22
This is great to hear! Thank you for sharing the code.

I can see why referencing the page would be hard when it doesn't exist yet 😅. I'd be interested to hear how you end up solving this.

For now I'll close this issue – please consider sharing all of the implementation as a third-party addon for Wagtail if you get the time. It's a very cool feature, and I'm sure a lot of people with similar workflows would love to have this on their site.

**Closed by thibaudcolas** 2018-03-30 21:22 UTC
Labels: enhancement
